### ISSUE TITLE
WatsonSTT operator needs a functional logging

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.sttgateway#11]
The stt operator loggs a lot events as errors which are no errors. E.g.:

Operator STTResult[0]-->Channel 0-->Received new/refreshed access token
Channel 0-->Websocket connection attempt 1 to the Watson STT service.

We should use error logs only for critical events and not for normal events.

**Comment by nysenthil** [comment]
Hi Joerg,
I'm still making a few more changes based on an important customer request. Please keep making a list of your good suggestions. Let us discuss this on a WebEx call sometime in November or December of 2019 and decide what is the best approach for every suggestion.

**Comment by joergboe** [comment]
Resolved with release 2.0.0
