### ISSUE TITLE
Samples should present results at console

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.sttgateway#12]
Samples should present results at console and not as an error-log. This confuses the user to find the result of the sample between all the unnecessary error logs. see also #11

**Comment by nysenthil** [comment]
Hi Joerg,
I'm still making a few more changes based on an important customer request. Please keep making a list of your good suggestions. Let us discuss this on a WebEx call sometime in November or December of 2019 and decide what is the best approach for every suggestion.

**Comment by joergboe** [comment]
Resolved with release 2.0.0
