### ISSUE TITLE
Potential Ressource Problem

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.sttgateway#29]
The WatsonSTT operator queues incomming tuples independent of the operational state of the stt service. Thus when the STT service is not operational, this queue may grow over all limits.
I propose that the operators throws away the oldest input tuples, when a certain limit is reached.

**Comment by ghost** [comment]
Maximum queue size as optional operator parameter?, default = ?

**Comment by joergboe** [comment]
Or probably delegate this problems to a threaded port.

**Comment by joergboe** [comment]
Issue is releated to #26

**Comment by joergboe** [comment]
Resolved with release 2.0.0
