### ISSUE TITLE
Warning during generation of spldoc-samples

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.sttgateway#61]
The command 
`ant spldoc-samples`
emits a lot of warning when generating doc for sample `VoiceGatewayToStreamsToWatsonSTT` and `VoiceGatewayToStreamsToWatsonS2T`.
This was not the case in the previous release!

**Comment by nysenthil** [comment]
Hi Joerg,
I made bulk changes to these two examples with the important new call recording and call replay features that we have been using at a large customer for the past three months. As part of that, I had to write a ton of commentary to explain how the new features are implemented. I may have accidentally removed the doc annotations. I have another revision coming up for these two examples shortly in late July based on another request from that customer. I will fix the doc errors at that time.

**Comment by nysenthil** [comment]
This got fixed today in v2.2.4.
